dbt_transformations:
  outputs:
    dev:
      dataset: "{{ env_var('BQ_DATASET', 'citibike_dev')}}"
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS', '../config/service-account.json') }}"
      location: US
      method: service-account
      priority: interactive
      project: "{{ env_var('GCP_PROJECT_ID', 'citibike-pipeline')}}"
      threads: 4
      type: bigquery
    prod:
      dataset: "{{ env_var('BQ_DATASET', 'citibike')}}"
      job_execution_timeout_seconds: 600
      job_retries: 1
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS', '../config/service-account.json') }}"
      location: US
      method: service-account
      priority: interactive
      project: "{{ env_var('GCP_PROJECT_ID', 'citibike-pipeline')}}"
      threads: 8
      type: bigquery
  target: dev
