version: 2

sources:
  - name: raw
    description: "Raw Citibike data ingested via custom pipeline"
    database: "{{ target.project }}"
    schema: "{{ 'raw' if target.name == 'prod' else 'raw_dev' }}"
    tables:
      - name: citibike_trips_legacy
        description: "Legacy trip data (2013-2019) with original schema"
        columns:
          - name: starttime
            description: "Trip start timestamp"
          - name: stoptime  
            description: "Trip end timestamp"
          - name: _batch_key
            description: "Batch identifier for incremental processing"
            
      - name: citibike_trips_current
        description: "Current trip data (2020+) with updated schema"  
        columns:
          - name: started_at
            description: "Trip start timestamp"
          - name: ended_at
            description: "Trip end timestamp" 
          - name: _batch_key
            description: "Batch identifier for incremental processing"
      - name: citibike_stations
        description: "Station data from GBFS feed"
        columns:
          - name: station_id
            description: "Unique id of station"
          - name: station_data
            description: "JSON string of station data from GBFS"
          - name: api_last_updated
            description: "Timestamp of last update to stations"
          - name: api_version
            desccription: "GBFS api version"
          - name: _ingested_at
            description: "When the GBFS data was accessed"
      - name: nyc_borough_boundaries
        description: "Geojson data for NYC borough boundaries"
        columns:
          - name: borough_code
            description: "1 = Manhattan, 2 = Bronx, 3 = Brooklyn, 4 = Queens, 5 = Staten Island"
          - name: borough_name
            description: "Name of the borough"
          - name: feature_geojson
            description: "JSON dump of complete geojson feature as string"
          - name: _ingested_at
            description: "When the data was accessed"
